const PASSWORD_MIN_LENGTH = 6;
const PASSWORD_MAX_LENGTH = 40;
const USER_MIN_LENGTH = 6;
const USER_MAX_LENGTH = 20;
export { PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, USER_MIN_LENGTH, USER_MAX_LENGTH };
