import { fontFamily, fontSize, fontWeight } from './font';

export default {
  displayLarge: {
    fontSize: fontSize.xxxLarge,
    lineHeight: '64px',
    fontWeight: fontWeight.normal,
    letterSpacing: 0,
    fontFamily,
  },
  displayMedium: {
    fontSize: fontSize.xxLarge,
    lineHeight: '52px',
    fontWeight: fontWeight.normal,
    letterSpacing: 0,
    fontFamily,
  },
  displaySmall: {
    fontSize: fontSize.xLarge,
    lineHeight: '44px',
    fontWeight: fontWeight.normal,
    letterSpacing: 0,
    fontFamily,
  },
  headlineLarge: {
    fontSize: fontSize.large,
    lineHeight: '40px',
    fontWeight: fontWeight.normal,
    letterSpacing: 0,
    fontFamily,
  },
  headlineMedium: {
    fontSize: fontSize.xxxxMedium,
    lineHeight: '32px',
    fontWeight: fontWeight.normal,
    letterSpacing: 0,
    fontFamily,
  },
  headlineSmall: {
    fontSize: fontSize.xxxMedium,
    lineHeight: '36px',
    fontWeight: fontWeight.normal,
    letterSpacing: 0,
    fontFamily,
  },
  titleLarge: {
    fontSize: fontSize.xxMedium,
    lineHeight: '28px',
    fontWeight: fontWeight.medium,
    letterSpacing: 0,
    fontFamily,
  },
  titleMedium: {
    fontSize: fontSize.xMedium,
    lineHeight: '24px',
    fontWeight: fontWeight.medium,
    letterSpacing: '0.15px',
    fontFamily,
  },
  titleSmall: {
    fontSize: fontSize.medium,
    lineHeight: '20px',
    fontWeight: fontWeight.medium,
    letterSpacing: '0.1px',
    fontFamily,
  },
  labelLarge: {
    fontSize: fontSize.medium,
    lineHeight: '20px',
    fontWeight: fontWeight.medium,
    letterSpacing: '0.1px',
    fontFamily,
  },
  labelMedium: {
    fontSize: fontSize.xxSmall,
    lineHeight: '16px',
    fontWeight: fontWeight.medium,
    letterSpacing: '0.5px',
    fontFamily,
  },
  labelSmall: {
    fontSize: fontSize.xSmall,
    lineHeight: '16px',
    fontWeight: fontWeight.medium,
    letterSpacing: '0.5px',
    fontFamily,
  },
  bodyLarge: {
    fontSize: fontSize.xMedium,
    lineHeight: '24px',
    fontWeight: fontWeight.normal,
    letterSpacing: '0.5px',
    fontFamily,
  },
  bodyMedium: {
    fontSize: fontSize.medium,
    lineHeight: '20px',
    fontWeight: fontWeight.normal,
    letterSpacing: '0.25px',
    fontFamily,
  },
  bodySmall: {
    fontSize: fontSize.xxSmall,
    lineHeight: '16px',
    fontWeight: fontWeight.normal,
    letterSpacing: '0.4px',
    fontFamily,
  },
  caption: {
    fontSize: fontSize.small,
    lineHeight: '16px',
    fontWeight: fontWeight.normal,
    letterSpacing: '0.6px',
    fontFamily,
  },
  button: {
    fontSize: fontSize.button,
    lineHeight: '24px',
    fontWeight: fontWeight.medium,
    letterSpacing: '0.15px',
    fontFamily,
  },
};
